### ISSUE TITLE
HPX Backend Restoration Tracer

### ISSUE THREAD

**Issue by gentryx** [gentryx/libgeodecomp#4]
The HpxSimulator won't work with HPX trunk since hpx::util::locality_results() was removed in https://github.com/STEllAR-GROUP/hpx/commit/d14e59551bd8aad30437f0d7d3af1bba15989266 and the new serialization infrastructure was introduced. This ticket serves as a tracer to track the work related to fixing the backend. The basic strategy is to disable all HPX related classes and then re-enabling them one by one, adding tests on the go. (We did lack tests for the HPX backend for quite a while which contributed to its brittleness). Tasks:

- [x] extend [TypemapGenerator](https://github.com/gentryx/libgeodecomp/tree/master/tools/typemapgenerator) to create a separate header for HPX serialization. The generator needs to be adaptable independently from the boost::serialization generator.
- [x] change CMake scripts so that hpx_main() will run by default on all localities (saves us the potentially costly initial broadcast)
- [x] extend serialization code within HPX to meet our requirements ([pending](https://github.com/STEllAR-GROUP/hpx/pull/1680))
- [x] add unit tests for serialization of the following classes (and their children)
  - [x] Writer
  - [x] SerialBOVWriter
  - [x] PPMWriter
  - [x] ParallelWriter
  - [x] OozeBalancer
  - [x] Steerer
  - [x] Initializer
  - [x] LoadBalancer
  - [x] FixedArray
  - [x] Selector
  - [x] Coord
  - [x] FloatCoord
  - [x] CoordBox
  - [x] Streak
  - [x] Region
- [x] prototype intantiation/communication/synchronization infrastructure with HPX primitives
- [x] add unit tests for [HpxSimulator::CreateUpdateGroups](https://github.com/gentryx/libgeodecomp/blob/master/src/parallelization/hpxsimulator/createupdategroups.h)
- [x] add unit tests for [HpxSimulator::HPXStepper](https://github.com/gentryx/libgeodecomp/blob/master/src/parallelization/hpxsimulator/hpxstepper.h)
- [x] add unit tests for [HpxSimulator::PatchLink](https://github.com/gentryx/libgeodecomp/blob/master/src/parallelization/hpxsimulator/patchlink.h)
- [x] add unit tests for [HpxSimulator::UpdateGroup](https://github.com/gentryx/libgeodecomp/blob/master/src/parallelization/hpxsimulator/updategroup.h)
- [x] add basic unit tests for HpxSimulator
- [x] add extended unit tests with better coverage for HpxSimulator

**Comment by sithhell** [comment]
> change CMake scripts so that hpx_main() will run by default on all localities (saves us the potentially costly initial broadcast)

We still need a initial broadcast for knowing the number of partitions and weights etc. but it should in general improve the picture because it will only need the broadcast in the initialization phase, not when starting the simulation.

**Comment by gentryx** [comment]
Pending merge.

**Comment by gentryx** [comment]
...and integration tests.

**Comment by gentryx** [comment]
fixed
